using System.Numerics;
using Content.Client._CMU14.UserInterface.Options;
using Content.Client.Stylesheets;
using Content.Shared.CMU14.Input;
using Content.Shared._RMC14.Input;
using Content.Shared.CCVar;
using Content.Shared.Chat.Prototypes;
using Content.Shared.Input;
using Content.Shared.Speech;
using Content.Shared.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.Input;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client.Options.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class KeyRebindTab : Control
    {
        // List of key functions that must be registered as toggle instead.
        private static readonly HashSet<BoundKeyFunction> ToggleFunctions = new()
        {
            EngineKeyFunctions.ShowDebugMonitors,
            EngineKeyFunctions.HideUI,
        };

        // The real human mob prototype (not MobHumanDummy, the lightweight preview-only entity)
        // used to figure out which emotes a Human can actually perform.
        private const string HumanMobPrototype = "MobHuman";

        [Dependency] private IInputManager _inputManager = default!;
        [Dependency] private IConfigurationManager _cfg = default!;
        [Dependency] private IEntityManager _entityManager = default!;
        [Dependency] private IPrototypeManager _prototypeManager = default!;

        private BindButton? _currentlyRebinding;

        private readonly Dictionary<BoundKeyFunction, KeyControl> _keyControls =
            new();

        private readonly List<Action> _deferCommands = new();

        private void InitToggleWalk()
        {
            if (_cfg.GetCVar(CCVars.ToggleWalk))
            {
                ToggleFunctions.Add(EngineKeyFunctions.Walk);
            }
            else
            {
                ToggleFunctions.Remove(EngineKeyFunctions.Walk);
            }
        }

        private void HandleToggleWalk(BaseButton.ButtonToggledEventArgs args)
        {
            _cfg.SetCVar(CCVars.ToggleWalk, args.Pressed);
            _cfg.SaveToFile();
            InitToggleWalk();

            if (!_keyControls.TryGetValue(EngineKeyFunctions.Walk, out var keyControl))
            {
                return;
            }

            var bindingType = args.Pressed ? KeyBindingType.Toggle : KeyBindingType.State;
            for (var i = 0; i <= 1; i++)
            {
                var binding = (i == 0 ? keyControl.BindButton1 : keyControl.BindButton2).Binding;
                if (binding == null)
                {
                    continue;
                }

                var registration = new KeyBindingRegistration
                {
                    Function = EngineKeyFunctions.Walk,
                    BaseKey = binding.BaseKey,
                    Mod1 = binding.Mod1,
                    Mod2 = binding.Mod2,
                    Mod3 = binding.Mod3,
                    Priority = binding.Priority,
                    Type = bindingType,
                    CanFocus = binding.CanFocus,
                    CanRepeat = binding.CanRepeat,
                };

                _deferCommands.Add(() =>
                {
                    _inputManager.RemoveBinding(binding);
                    _inputManager.RegisterBinding(registration);
                });
            }

            _deferCommands.Add(_inputManager.SaveToUserData);
        }

        // Emotes usable by a bare Human, for the emote-keybind pickers below. Creates a throwaway
        // uninitialized copy of the actual human mob (not the lightweight character-preview dummy,
        // which is missing Hands/Vocal/Speech/etc. and would fail almost every emote whitelist)
        // so the same whitelist/blacklist checks the emotes wheel uses can run without triggering
        // normal mob startup or shutdown side effects.
        private List<EmotePrototype> GetHumanAvailableEmotes()
        {
            var result = new List<EmotePrototype>();

            try
            {
                if (!_prototypeManager.HasIndex<EntityPrototype>(HumanMobPrototype))
                    return result;

                var whitelistSystem = _entityManager.System<EntityWhitelistSystem>();
                var dummy = _entityManager.CreateEntityUninitialized(HumanMobPrototype);

                try
                {
                    _entityManager.TryGetComponent<SpeechComponent>(dummy, out var speech);

                    foreach (var emote in _prototypeManager.EnumeratePrototypes<EmotePrototype>())
                    {
                        if (emote.Category == EmoteCategory.Invalid || emote.ChatTriggers.Count == 0)
                            continue;

                        if (!whitelistSystem.IsWhitelistPassOrNull(emote.Whitelist, dummy))
                            continue;

                        if (whitelistSystem.IsWhitelistPass(emote.Blacklist, dummy))
                            continue;

                        if (!emote.Available && (speech == null || !speech.AllowedEmotes.Contains(emote.ID)))
                            continue;

                        result.Add(emote);
                    }
                }
                finally
                {
                    _entityManager.DeleteEntity(dummy);
                }
            }
            catch (Exception)
            {
                // Never let a failure here (e.g. no active entity context yet) take down the whole options menu.
                return result;
            }

            result.Sort((a, b) => string.Compare(Loc.GetString(a.Name), Loc.GetString(b.Name), StringComparison.Ordinal));
            return result;
        }

        private void HandleStaticStorageUI(BaseButton.ButtonToggledEventArgs args)
        {
            _cfg.SetCVar(CCVars.StaticStorageUI, args.Pressed);
            _cfg.SaveToFile();
        }

        public KeyRebindTab()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            ResetAllButton.OnPressed += _ =>
            {
                _deferCommands.Add(() =>
                {
                    _inputManager.ResetAllBindings();
                    _inputManager.SaveToUserData();
                });
            };

            // Each header opens a collapsible section and everything after it goes inside, matching
            // the other options tabs. This tab is the longest of them by far, so folding matters
            // most here.
            CmuOptionSection? section = null;

            void AddTo(Control child)
            {
                if (section == null)
                    KeybindsContainer.AddChild(child);
                else
                    section.AddOption(child);
            }

            void AddHeader(string headerContents)
            {
                section = new CmuOptionSection { Title = Loc.GetString(headerContents) };
                KeybindsContainer.AddChild(section);
            }

            void AddButton(BoundKeyFunction function)
            {
                var control = new KeyControl(this, function);
                AddTo(control);
                _keyControls.Add(function, control);
            }

            void AddCheckBox(string checkBoxName, bool currentState, Action<BaseButton.ButtonToggledEventArgs>? callBackOnClick)
            {
                CheckBox newCheckBox = new CheckBox() { Text = Loc.GetString(checkBoxName) };
                newCheckBox.Pressed = currentState;
                newCheckBox.OnToggled += callBackOnClick;

                AddTo(newCheckBox);
            }

            void AddToggleCvarCheckBox(string checkBoxName, CVarDef<bool> cvar)
            {
                var newCheckBox = new CheckBox { Text = Loc.GetString(checkBoxName) };
                newCheckBox.Pressed = _cfg.GetCVar(cvar);
                newCheckBox.OnToggled += args =>
                {
                    _cfg.SetCVar(cvar, args.Pressed);
                    _cfg.SaveToFile();
                };

                AddTo(newCheckBox);
            }

            AddHeader("ui-options-header-rmc");
            AddButton(CMKeyFunctions.RMCActivateAttachableBarrel);
            AddButton(CMKeyFunctions.RMCActivateAttachableRail);
            AddButton(CMKeyFunctions.RMCActivateAttachableStock);
            AddButton(CMKeyFunctions.RMCActivateAttachableUnderbarrel);
            AddButton(CMKeyFunctions.RMCFieldStripHeldItem);
            AddButton(CMKeyFunctions.RMCCycleFireMode);
            AddButton(CMKeyFunctions.CMUniqueAction);
            AddButton(CMKeyFunctions.CMHolsterPrimary);
            AddButton(CMKeyFunctions.CMHolsterSecondary);
            AddButton(CMKeyFunctions.CMHolsterTertiary);
            AddButton(CMKeyFunctions.CMHolsterQuaternary);
            AddButton(CMKeyFunctions.RMCPickUpDroppedItems);
            AddButton(CMKeyFunctions.RMCInteractWithOtherHand);
            AddButton(CMKeyFunctions.RMCRest);

            AddHeader("ui-options-header-cmu-medical");
            AddButton(CMUKeyFunctions.CMUCycleBodyZoneTarget);
            AddButton(CMUKeyFunctions.CMUCycleBodyZoneTargetReverse);
            AddButton(CMUKeyFunctions.CMUTargetBodyZoneHead);
            AddButton(CMUKeyFunctions.CMUTargetBodyZoneTorso);
            AddButton(CMUKeyFunctions.CMUTargetBodyZoneLeftArm);
            AddButton(CMUKeyFunctions.CMUTargetBodyZoneRightArm);
            AddButton(CMUKeyFunctions.CMUTargetBodyZoneLeftLeg);
            AddButton(CMUKeyFunctions.CMUTargetBodyZoneRightLeg);
            AddButton(CMUKeyFunctions.CMUOpenMedicalCraftingMenu);

            AddHeader("ui-options-header-cmu-zlevels");
            AddButton(CMUKeyFunctions.CMUToggleShootDownZLevel);

            AddHeader("ui-options-header-cmu-gunship");
            AddButton(CMUKeyFunctions.CMUGunshipForward);
            AddButton(CMUKeyFunctions.CMUGunshipBack);
            AddButton(CMUKeyFunctions.CMUGunshipLeft);
            AddButton(CMUKeyFunctions.CMUGunshipRight);
            AddButton(CMUKeyFunctions.CMUGunshipRotateLeft);
            AddButton(CMUKeyFunctions.CMUGunshipRotateRight);
            AddButton(CMUKeyFunctions.CMUGunshipAscend);
            AddButton(CMUKeyFunctions.CMUGunshipDescend);
            AddButton(CMUKeyFunctions.CMUGunshipIncreaseThrust);
            AddButton(CMUKeyFunctions.CMUGunshipDecreaseThrust);
            AddButton(CMUKeyFunctions.CMUGunshipCycleCamera);
            AddButton(CMUKeyFunctions.CMUGunshipTogglePanning);

            AddHeader("ui-options-header-rmc-xeno");
            AddButton(CMKeyFunctions.CMXenoWideSwing);
            AddButton(CMKeyFunctions.RMCXenoRest);

            AddHeader("ui-options-header-cmu-emotes");
            AddButton(CMUKeyFunctions.CMUEmoteSlot1);
            AddButton(CMUKeyFunctions.CMUEmoteSlot2);
            AddButton(CMUKeyFunctions.CMUEmoteSlot3);
            AddButton(CMUKeyFunctions.CMUEmoteSlot4);
            AddButton(CMUKeyFunctions.CMUEmoteSlot5);
            AddButton(CMUKeyFunctions.CMUEmoteSlot6);
            AddButton(CMUKeyFunctions.CMUEmoteSlot7);
            AddButton(CMUKeyFunctions.CMUEmoteSlot8);

            var humanEmotes = GetHumanAvailableEmotes();

            void AddEmoteSlot(string labelLoc, CVarDef<string> cvar)
            {
                var button = new OptionButton();
                button.AddItem(Loc.GetString("cmu-ui-options-emote-slot-none"), 0);

                var current = _cfg.GetCVar(cvar);
                var selected = 0;
                for (var i = 0; i < humanEmotes.Count; i++)
                {
                    button.AddItem(Loc.GetString(humanEmotes[i].Name), i + 1);
                    if (humanEmotes[i].ID == current)
                        selected = i + 1;
                }

                button.SelectId(selected);
                button.OnItemSelected += args =>
                {
                    button.SelectId(args.Id);
                    _cfg.SetCVar(cvar, args.Id == 0 ? string.Empty : humanEmotes[args.Id - 1].ID);
                    _cfg.SaveToFile();
                };

                var row = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        new Control { MinSize = new Vector2(5, 0) },
                        new Label
                        {
                            Text = Loc.GetString(labelLoc),
                            HorizontalExpand = true,
                            HorizontalAlignment = HAlignment.Left
                        },
                        button
                    }
                };

                AddTo(row);
            }

            AddEmoteSlot("cmu-ui-options-emote-slot-1", CCVars.EmoteSlot1);
            AddEmoteSlot("cmu-ui-options-emote-slot-2", CCVars.EmoteSlot2);
            AddEmoteSlot("cmu-ui-options-emote-slot-3", CCVars.EmoteSlot3);
            AddEmoteSlot("cmu-ui-options-emote-slot-4", CCVars.EmoteSlot4);
            AddEmoteSlot("cmu-ui-options-emote-slot-5", CCVars.EmoteSlot5);
            AddEmoteSlot("cmu-ui-options-emote-slot-6", CCVars.EmoteSlot6);
            AddEmoteSlot("cmu-ui-options-emote-slot-7", CCVars.EmoteSlot7);
            AddEmoteSlot("cmu-ui-options-emote-slot-8", CCVars.EmoteSlot8);

            AddHeader("ui-options-header-general");
            AddToggleCvarCheckBox("ui-options-hotkey-keymap", CVars.DisplayUSQWERTYHotkeys);
            AddToggleCvarCheckBox("ui-options-hold-to-attack-melee", CCVars.ControlHoldToAttackMelee);
            AddToggleCvarCheckBox("ui-options-hold-to-attack-ranged", CCVars.ControlHoldToAttackRanged);

            AddHeader("ui-options-header-movement");
            AddButton(EngineKeyFunctions.MoveUp);
            AddButton(EngineKeyFunctions.MoveLeft);
            AddButton(EngineKeyFunctions.MoveDown);
            AddButton(EngineKeyFunctions.MoveRight);
            AddButton(EngineKeyFunctions.Walk);
            AddCheckBox("ui-options-hotkey-toggle-walk", _cfg.GetCVar(CCVars.ToggleWalk), HandleToggleWalk);
            InitToggleWalk();
            AddButton(ContentKeyFunctions.ToggleKnockdown);

            AddHeader("ui-options-header-camera");
            AddButton(EngineKeyFunctions.CameraRotateLeft);
            AddButton(EngineKeyFunctions.CameraRotateRight);
            AddButton(EngineKeyFunctions.CameraReset);
            AddButton(ContentKeyFunctions.RotateCameraWithMouse);
            AddButton(ContentKeyFunctions.ZoomIn);
            AddButton(ContentKeyFunctions.ZoomOut);
            AddButton(ContentKeyFunctions.ResetZoom);

            AddHeader("ui-options-header-interaction-basic");
            AddButton(EngineKeyFunctions.Use);
            AddButton(EngineKeyFunctions.UseSecondary);
            AddButton(ContentKeyFunctions.UseItemInHand);
            AddButton(ContentKeyFunctions.AltUseItemInHand);
            AddButton(ContentKeyFunctions.ActivateItemInWorld);
            AddButton(ContentKeyFunctions.AltActivateItemInWorld);
            AddButton(ContentKeyFunctions.Drop);
            AddButton(ContentKeyFunctions.ExamineEntity);
            AddButton(ContentKeyFunctions.SwapHands);
            AddButton(ContentKeyFunctions.SwapHandsReverse);
            AddButton(ContentKeyFunctions.MoveStoredItem);
            AddButton(ContentKeyFunctions.RotateStoredItem);
            AddButton(ContentKeyFunctions.SaveItemLocation);

            AddHeader("ui-options-header-interaction-adv");
            AddButton(ContentKeyFunctions.SmartEquipBackpack);
            AddButton(ContentKeyFunctions.SmartEquipBelt);
            AddButton(ContentKeyFunctions.SmartEquipPocket1);
            AddButton(ContentKeyFunctions.SmartEquipPocket2);
            AddButton(ContentKeyFunctions.SmartEquipSuitStorage);
            // RMC14
            AddButton(ContentKeyFunctions.SmartEquipUniform);
            AddButton(ContentKeyFunctions.SmartEquipArmor);
            AddButton(ContentKeyFunctions.SmartEquipHelmet);
            // RMC14
            AddButton(ContentKeyFunctions.OpenBackpack);
            AddButton(ContentKeyFunctions.OpenBelt);
            AddButton(ContentKeyFunctions.ThrowItemInHand);
            AddButton(ContentKeyFunctions.TryPullObject);
            AddButton(ContentKeyFunctions.MovePulledObject);
            AddButton(ContentKeyFunctions.ReleasePulledObject);
            AddButton(ContentKeyFunctions.Point);
            AddButton(ContentKeyFunctions.RotateObjectClockwise);
            AddButton(ContentKeyFunctions.RotateObjectCounterclockwise);
            AddButton(ContentKeyFunctions.FlipObject);

            AddHeader("ui-options-header-ui");
            AddButton(ContentKeyFunctions.FocusChat);
            AddButton(ContentKeyFunctions.FocusLocalChat);
            AddButton(ContentKeyFunctions.FocusEmote);
            AddButton(ContentKeyFunctions.FocusWhisperChat);
            AddButton(ContentKeyFunctions.FocusRadio);
            AddButton(ContentKeyFunctions.FocusLOOC);
            AddButton(ContentKeyFunctions.FocusOOC);
            AddButton(ContentKeyFunctions.FocusAdminChat);
            AddButton(ContentKeyFunctions.FocusDeadChat);
            AddButton(ContentKeyFunctions.FocusConsoleChat);
            AddButton(ContentKeyFunctions.CycleChatChannelForward);
            AddButton(ContentKeyFunctions.CycleChatChannelBackward);
            AddButton(ContentKeyFunctions.OpenCharacterMenu);
            AddButton(ContentKeyFunctions.OpenCraftingMenu);
            AddButton(ContentKeyFunctions.OpenGuidebook);
            AddButton(ContentKeyFunctions.OpenInventoryMenu);
            AddButton(ContentKeyFunctions.OpenAHelp);
            AddButton(ContentKeyFunctions.OpenActionsMenu);
            AddButton(ContentKeyFunctions.OpenEmotesMenu);
            AddButton(ContentKeyFunctions.ToggleRoundEndSummaryWindow);
            AddButton(ContentKeyFunctions.OpenEntitySpawnWindow);
            AddButton(ContentKeyFunctions.OpenSandboxWindow);
            AddButton(ContentKeyFunctions.OpenTileSpawnWindow);
            AddButton(ContentKeyFunctions.OpenDecalSpawnWindow);
            AddButton(ContentKeyFunctions.OpenAdminMenu);
            AddButton(EngineKeyFunctions.WindowCloseAll);
            AddButton(EngineKeyFunctions.WindowCloseRecent);
            AddButton(EngineKeyFunctions.EscapeMenu);
            AddButton(ContentKeyFunctions.EscapeContext);

            AddHeader("ui-options-header-misc");
            AddButton(ContentKeyFunctions.TakeScreenshot);
            AddButton(ContentKeyFunctions.TakeScreenshotNoUI);
            AddButton(ContentKeyFunctions.ToggleFullscreen);

            AddHeader("ui-options-header-hotbar");
            foreach (var boundKey in ContentKeyFunctions.GetHotbarBoundKeys())
            {
                AddButton(boundKey);
            }

            AddHeader("ui-options-header-shuttle");
            AddButton(ContentKeyFunctions.ShuttleStrafeUp);
            AddButton(ContentKeyFunctions.ShuttleStrafeRight);
            AddButton(ContentKeyFunctions.ShuttleStrafeLeft);
            AddButton(ContentKeyFunctions.ShuttleStrafeDown);
            AddButton(ContentKeyFunctions.ShuttleRotateLeft);
            AddButton(ContentKeyFunctions.ShuttleRotateRight);
            AddButton(ContentKeyFunctions.ShuttleBrake);

            AddHeader("ui-options-header-map-editor");
            AddButton(EngineKeyFunctions.EditorPlaceObject);
            AddButton(EngineKeyFunctions.EditorCancelPlace);
            AddButton(EngineKeyFunctions.EditorGridPlace);
            AddButton(EngineKeyFunctions.EditorLinePlace);
            AddButton(EngineKeyFunctions.EditorRotateObject);
            AddButton(ContentKeyFunctions.EditorFlipObject);
            AddButton(ContentKeyFunctions.EditorCopyObject);

            AddHeader("ui-options-header-dev");
            AddButton(EngineKeyFunctions.ShowDebugConsole);
            AddButton(EngineKeyFunctions.ShowDebugMonitors);
            AddButton(EngineKeyFunctions.HideUI);
            AddButton(ContentKeyFunctions.InspectEntity);
            AddButton(ContentKeyFunctions.InspectServerComponent);
            AddButton(ContentKeyFunctions.InspectClientComponent);

            AddHeader("ui-options-header-text-cursor");
            AddButton(EngineKeyFunctions.TextCursorLeft);
            AddButton(EngineKeyFunctions.TextCursorRight);
            AddButton(EngineKeyFunctions.TextCursorUp);
            AddButton(EngineKeyFunctions.TextCursorDown);
            AddButton(EngineKeyFunctions.TextCursorWordLeft);
            AddButton(EngineKeyFunctions.TextCursorWordRight);
            AddButton(EngineKeyFunctions.TextCursorBegin);
            AddButton(EngineKeyFunctions.TextCursorEnd);

            AddHeader("ui-options-header-text-cursor-select");
            AddButton(EngineKeyFunctions.TextCursorSelect);
            AddButton(EngineKeyFunctions.TextCursorSelectLeft);
            AddButton(EngineKeyFunctions.TextCursorSelectRight);
            AddButton(EngineKeyFunctions.TextCursorSelectUp);
            AddButton(EngineKeyFunctions.TextCursorSelectDown);
            AddButton(EngineKeyFunctions.TextCursorSelectWordLeft);
            AddButton(EngineKeyFunctions.TextCursorSelectWordRight);
            AddButton(EngineKeyFunctions.TextCursorSelectBegin);
            AddButton(EngineKeyFunctions.TextCursorSelectEnd);

            AddHeader("ui-options-header-text-edit");
            AddButton(EngineKeyFunctions.TextBackspace);
            AddButton(EngineKeyFunctions.TextDelete);
            AddButton(EngineKeyFunctions.TextWordBackspace);
            AddButton(EngineKeyFunctions.TextWordDelete);
            AddButton(EngineKeyFunctions.TextNewline);
            AddButton(EngineKeyFunctions.TextSubmit);
            AddButton(EngineKeyFunctions.MultilineTextSubmit);
            AddButton(EngineKeyFunctions.TextSelectAll);
            AddButton(EngineKeyFunctions.TextCopy);
            AddButton(EngineKeyFunctions.TextCut);
            AddButton(EngineKeyFunctions.TextPaste);

            AddHeader("ui-options-header-text-chat");
            AddButton(EngineKeyFunctions.TextHistoryPrev);
            AddButton(EngineKeyFunctions.TextHistoryNext);
            AddButton(EngineKeyFunctions.TextReleaseFocus);
            AddButton(EngineKeyFunctions.TextScrollToBottom);

            AddHeader("ui-options-header-text-other");
            AddButton(EngineKeyFunctions.TextTabComplete);
            AddButton(EngineKeyFunctions.TextCompleteNext);
            AddButton(EngineKeyFunctions.TextCompletePrev);

            foreach (var control in _keyControls.Values)
            {
                UpdateKeyControl(control);
            }
        }

        private void UpdateKeyControl(KeyControl control)
        {
            var activeBinds = _inputManager.GetKeyBindings(control.Function);

            IKeyBinding? bind1 = null;
            IKeyBinding? bind2 = null;

            if (activeBinds.Count > 0)
            {
                bind1 = activeBinds[0];

                if (activeBinds.Count > 1)
                {
                    bind2 = activeBinds[1];
                }
            }

            control.BindButton1.Binding = bind1;
            control.BindButton1.UpdateText();

            control.BindButton2.Binding = bind2;
            control.BindButton2.UpdateText();

            control.BindButton2.Button.Disabled = activeBinds.Count == 0;
            control.ResetButton.Disabled = !_inputManager.IsKeyFunctionModified(control.Function);
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();

            _inputManager.FirstChanceOnKeyEvent += InputManagerOnFirstChanceOnKeyEvent;
            _inputManager.OnKeyBindingAdded += OnKeyBindAdded;
            _inputManager.OnKeyBindingRemoved += OnKeyBindRemoved;
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();

            _inputManager.FirstChanceOnKeyEvent -= InputManagerOnFirstChanceOnKeyEvent;
            _inputManager.OnKeyBindingAdded -= OnKeyBindAdded;
            _inputManager.OnKeyBindingRemoved -= OnKeyBindRemoved;
        }

        private void OnKeyBindRemoved(IKeyBinding obj)
        {
            OnKeyBindModified(obj, true);
        }

        private void OnKeyBindAdded(IKeyBinding obj)
        {
            OnKeyBindModified(obj, false);
        }

        private void OnKeyBindModified(IKeyBinding bind, bool removal)
        {
            if (!_keyControls.TryGetValue(bind.Function, out var keyControl))
            {
                return;
            }

            if (removal && _currentlyRebinding?.KeyControl == keyControl)
            {
                // Don't do update if the removal was from initiating a rebind.
                return;
            }

            UpdateKeyControl(keyControl);

            if (_currentlyRebinding == keyControl.BindButton1 || _currentlyRebinding == keyControl.BindButton2)
            {
                _currentlyRebinding = null;
            }
        }

        private void InputManagerOnFirstChanceOnKeyEvent(KeyEventArgs keyEvent, KeyEventType type)
        {
            DebugTools.Assert(IsInsideTree);

            if (_currentlyRebinding == null)
            {
                return;
            }

            keyEvent.Handle();

            if (type != KeyEventType.Up)
            {
                return;
            }

            var key = keyEvent.Key;

            // Figure out modifiers based on key event.
            // TODO: this won't allow for combinations with keys other than the standard modifier keys,
            // even though the input system totally supports it.
            var mods = new Keyboard.Key[3];
            var i = 0;
            if (keyEvent.Control && key != Keyboard.Key.Control)
            {
                mods[i] = Keyboard.Key.Control;
                i += 1;
            }

            if (keyEvent.Shift && key != Keyboard.Key.Shift)
            {
                mods[i] = Keyboard.Key.Shift;
                i += 1;
            }

            if (keyEvent.Alt && key != Keyboard.Key.Alt)
            {
                mods[i] = Keyboard.Key.Alt;
                i += 1;
            }

            // The input system can only handle 3 modifier keys so if you hold all 4 of the modifier keys
            // then system gets the shaft, I guess.
            if (keyEvent.System && i != 3 && key != Keyboard.Key.LSystem && key != Keyboard.Key.RSystem)
            {
                mods[i] = Keyboard.Key.LSystem;
            }

            var function = _currentlyRebinding.KeyControl.Function;
            var bindType = KeyBindingType.State;
            if (ToggleFunctions.Contains(function))
            {
                bindType = KeyBindingType.Toggle;
            }

            var registration = new KeyBindingRegistration
            {
                Function = function,
                BaseKey = key,
                Mod1 = mods[0],
                Mod2 = mods[1],
                Mod3 = mods[2],
                Priority = _currentlyRebinding.Binding?.Priority ?? 0,
                Type = bindType,
                CanFocus = key == Keyboard.Key.MouseLeft
                           || key == Keyboard.Key.MouseRight
                           || key == Keyboard.Key.MouseMiddle,
                CanRepeat = false
            };

            _inputManager.RegisterBinding(registration);
            // OnKeyBindModified will cause _currentlyRebinding to be reset and the UI to update.
            _inputManager.SaveToUserData();
        }

        private void RebindButtonPressed(BindButton button)
        {
            if (_currentlyRebinding != null)
            {
                return;
            }

            _currentlyRebinding = button;
            _currentlyRebinding.Button.Text = Loc.GetString("ui-options-key-prompt");

            if (button.Binding != null)
            {
                _deferCommands.Add(() =>
                {
                    // Have to do defer this or else there will be an exception in InputManager.
                    // Because this IS fired from an input event.
                    _inputManager.RemoveBinding(button.Binding);
                });
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            if (_deferCommands.Count == 0)
            {
                return;
            }

            foreach (var command in _deferCommands)
            {
                command();
            }

            _deferCommands.Clear();
        }

        private sealed partial class KeyControl : Control
        {
            public readonly BoundKeyFunction Function;
            public readonly BindButton BindButton1;
            public readonly BindButton BindButton2;
            public readonly Button ResetButton;

            public KeyControl(KeyRebindTab parent, BoundKeyFunction function)
            {
                Function = function;
                var name = new Label
                {
                    Text = Loc.GetString(
                        $"ui-options-function-{CaseConversion.PascalToKebab(function.FunctionName)}"),
                    HorizontalExpand = true,
                    HorizontalAlignment = HAlignment.Left
                };

                BindButton1 = new BindButton(parent, this, StyleClass.ButtonOpenRight);
                BindButton2 = new BindButton(parent, this, StyleClass.ButtonOpenLeft);
                ResetButton = new Button { Text = Loc.GetString("ui-options-bind-reset"), StyleClasses = { StyleClass.Negative } };

                var hBox = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        new Control {MinSize = new Vector2(5, 0)},
                        name,
                        BindButton1,
                        BindButton2,
                        new Control {MinSize = new Vector2(10, 0)},
                        ResetButton
                    }
                };

                ResetButton.OnPressed += args =>
                {
                    parent._deferCommands.Add(() =>
                    {
                        parent._inputManager.ResetBindingsFor(function);
                        parent._inputManager.SaveToUserData();
                    });
                };

                AddChild(hBox);
            }
        }

        private sealed partial class BindButton : Control
        {
            private readonly IResourceCache _resourceCache = IoCManager.Resolve<IResourceCache>();
            private readonly KeyRebindTab _tab;
            public readonly KeyControl KeyControl;
            public readonly Button Button;
            public IKeyBinding? Binding;

            public BindButton(KeyRebindTab tab, KeyControl keyControl, string styleClass)
            {
                _tab = tab;
                KeyControl = keyControl;
                Button = new Button { StyleClasses = { styleClass } };
                UpdateText();
                AddChild(Button);

                Button.OnPressed += args =>
                {
                    tab.RebindButtonPressed(this);
                };

                Button.OnKeyBindDown += ButtonOnOnKeyBindDown;

                // 200 left a lot of dead space around short binds like "F". Long combos are handled
                // by shrinking the label in UpdateText rather than by sizing every button for the
                // worst case.
                MinSize = new Vector2(140, 0);
            }

            protected override void EnteredTree()
            {
                base.EnteredTree();
                _tab._inputManager.OnInputModeChanged += UpdateText;
            }

            protected override void ExitedTree()
            {
                base.ExitedTree();
                _tab._inputManager.OnInputModeChanged -= UpdateText;
            }

            private void ButtonOnOnKeyBindDown(GUIBoundKeyEventArgs args)
            {
                if (args.Function == EngineKeyFunctions.UIRightClick)
                {
                    if (Binding != null)
                    {
                        _tab._deferCommands.Add(() =>
                        {
                            _tab._inputManager.RemoveBinding(Binding);
                            _tab._inputManager.SaveToUserData();
                        });
                    }

                    args.Handle();
                }
            }

            public void UpdateText()
            {
                var text = Binding?.GetKeyString() ?? Loc.GetString("ui-options-unbound");
                Button.Text = text;

                if (!StyleNano.CrtUiEnabled)
                    return;

                // Step the label down rather than let a combo like "CONTROL+NUMPAD ENTER" widen the
                // button past its column and knock the whole row out of alignment. FontOverride,
                // because the CRT rule sizes every button label through one parent-child selector
                // that a competing style class would only tie with.
                var size = text.Length switch
                {
                    > 17 => 6,
                    > 12 => 7,
                    _ => 8,
                };

                Button.Label.FontOverride = StyleNano.GetCrtFont(_resourceCache, size);
            }
        }
    }
}
