using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for color options in the options menu. Intended for use with <see cref="OptionsTabControlRow"/>.
/// </summary>
/// <seealso cref="OptionsTabControlRow.AddOptionColorSlider"/>
[GenerateTypedNameReferences]
public sealed partial class OptionColorSlider : Control
{
    /// <summary>
    /// Text placed before the color's name, e.g. "Your highlight color is:".
    /// </summary>
    public string? Title
    {
        get => Picker.Title;
        set => Picker.Title = value;
    }

    /// <summary>
    /// Id of a <c>colorPalette</c> prototype whose colors are offered as presets.
    /// </summary>
    public string? Palette
    {
        get => Picker.PaletteId;
        set => Picker.PaletteId = value;
    }
}
