using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for sliders in the options menu. Intended for use with <see cref="OptionsTabControlRow"/>.
/// </summary>
/// <seealso cref="OptionsTabControlRow.AddOptionSlider"/>
/// <seealso cref="OptionsTabControlRow.AddOptionPercentSlider"/>
[GenerateTypedNameReferences]
public sealed partial class OptionSlider : Control
{
    /// <summary>
    /// The text describing what this slider controls.
    /// </summary>
    public string? Title
    {
        get => NameLabel.Text;
        set => NameLabel.Text = value;
    }

    public OptionSlider()
    {
        RobustXamlLoader.Load(this);

        // The XAML wires the value box up for the CRT look - flush against the slider, no left
        // border - which only reads correctly because the CRT slider draws a matching frame around
        // its track for that box to continue. NanoUI's slider has no such frame, so in base mode the
        // box read as a fragment with a missing edge sitting with no gap from the track. Swap to the
        // closed, four-sided box and give it real separation.
        if (!StyleNano.CrtUiEnabled)
        {
            ValuePanel.RemoveStyleClass(StyleNano.StyleClassCrtSliderValue);
            ValuePanel.AddStyleClass(StyleNano.StyleClassNanoSliderValue);
            ValuePanel.Margin = new Thickness(6, 0, 0, 0);
        }
    }
}
