using Content.Client._CMU14.Interface;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._RMC14.Mentor;

[GenerateTypedNameReferences]
public sealed partial class StaffHelpWindow : DefaultWindow
{
    /// <summary>
    ///     Admin help. Red because this is the report-a-player channel - the one with consequences
    ///     at the end of it, and the one people should not open by accident.
    /// </summary>
    private static readonly CmuChoiceCard.Palette AdminPalette = new(
        Color.FromHex("#8C3038"), Color.FromHex("#170C0E"), Color.FromHex("#2A1417"), Color.FromHex("#FF9E9E"));

    /// <summary>Mentor help. Terminal green: asking a question is the ordinary, safe thing to do.</summary>
    private static readonly CmuChoiceCard.Palette MentorPalette = new(
        Color.FromHex("#2E6241"), Color.FromHex("#0B1710"), Color.FromHex("#152F20"), Color.FromHex("#8FE9AE"));

    /// <summary>
    ///     Kept as properties because <see cref="StaffHelpUIController"/> binds to them by name, and
    ///     the buttons now belong to the cards rather than to the XAML.
    /// </summary>
    public Button AdminHelpButton => _adminCard.Button;

    public Button MentorHelpButton => _mentorCard.Button;

    private readonly CmuChoiceCard _adminCard;
    private readonly CmuChoiceCard _mentorCard;

    public StaffHelpWindow()
    {
        RobustXamlLoader.Load(this);

        // Alternating sides, as in the join-round window: two identical rows read as a table, and a
        // zig-zag makes each one its own object. With only two choices it also puts the buttons at
        // opposite corners, so they are hard to hit by mistake - which matters when one of them
        // files a report about another player.
        _adminCard = new CmuChoiceCard(
            "Admin Help",
            "For reporting issues with another player to an admin, or asking about the rules.",
            AdminPalette,
            buttonOnLeft: true);

        _mentorCard = new CmuChoiceCard(
            "Mentor Help",
            "Talk to Mentors about questions you might have about the game mechanics, lore and such. Rule questions should go to Admin Help.",
            MentorPalette,
            buttonOnLeft: false);

        Choices.AddChild(_adminCard);
        Choices.AddChild(_mentorCard);
    }

    /// <summary>
    ///     Mark the mentor choice as having unread messages behind it.
    /// </summary>
    /// <remarks>
    ///     Replaces the <c>ButtonColorRed</c> style class the controller used to add. That stopped
    ///     working the moment these buttons got a StyleBoxOverride - an override beats any
    ///     stylesheet rule, so the class would have been added and simply never drawn, losing the
    ///     unread signal silently.
    /// </remarks>
    public void SetMentorUnread(bool unread)
    {
        _mentorCard.SetPalette(unread ? AdminPalette : MentorPalette);
    }

    /// <summary>
    ///     Re-assert the card colours once the window is in the tree.
    /// </summary>
    /// <remarks>
    ///     The controller runs its CRT chrome pass between construction and opening, and that pass
    ///     hands every button in the tree the shared CrtButton box - which would leave both cards
    ///     looking like ordinary controls. EnteredTree fires after it, so this is the first safe
    ///     moment to put the faction colours back.
    /// </remarks>
    protected override void EnteredTree()
    {
        base.EnteredTree();

        _adminCard.ApplyPalette();
        _mentorCard.ApplyPalette();
    }
}
