using System;
using Content.Client.Lobby.UI;
using Content.Client._CMU14.Interface;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._CMU14.Lobby;

/// <summary>
///     The faction choices, moved off the lobby panel and behind a single "Join the round" button.
///     Four wide buttons plus Observe, Rules and Guidebook made the lobby panel a seven-button slab;
///     the factions are one decision, taken once, so they belong in a popup rather than on the
///     permanent surface.
/// </summary>
/// <remarks>
///     Presentation only. What each choice does still lives in <c>LobbyState</c>, which wires these
///     buttons to the same handlers the old inline buttons used.
/// </remarks>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class JoinRoundWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IStylesheetManager _stylesheetManager = default!;

    /// <summary>
    ///     Colonists. The plain one on purpose - they are the default, least exotic choice, so it
    ///     gets a neutral grey-green rather than a faction colour. Being the only card with no hue
    ///     is itself the signal.
    /// </summary>
    private static readonly CmuChoiceCard.Palette ColonistsPalette = new(
        Color.FromHex("#5E6B64"), Color.FromHex("#0E1211"), Color.FromHex("#18201D"), Color.FromHex("#C2CCC6"));

    /// <summary>Govfor keeps the terminal green - it is the house faction and the theme's own hue.</summary>
    private static readonly CmuChoiceCard.Palette GovforPalette = new(
        Color.FromHex("#2E6241"), Color.FromHex("#0B1710"), Color.FromHex("#152F20"), Color.FromHex("#8FE9AE"));

    private static readonly CmuChoiceCard.Palette OpforPalette = new(
        Color.FromHex("#8C3038"), Color.FromHex("#170C0E"), Color.FromHex("#2A1417"), Color.FromHex("#FF9E9E"));

    /// <summary>Other - mostly xenomorphs, hence purple.</summary>
    private static readonly CmuChoiceCard.Palette OtherPalette = new(
        Color.FromHex("#5B4A8C"), Color.FromHex("#120E1B"), Color.FromHex("#1E1830"), Color.FromHex("#CDBCFF"));

    /// <summary>
    ///     Kept as properties because <see cref="Content.Client.Lobby.LobbyState"/> binds to them by
    ///     name, and the buttons now belong to the cards rather than to the XAML.
    /// </summary>
    public Button JoinColonistsButton => _colonists.Button;

    public Button JoinGovforButton => _govfor.Button;

    public Button JoinOpforButton => _opfor.Button;

    public Button JoinOtherButton => _other.Button;

    private readonly CmuChoiceCard _colonists;
    private readonly CmuChoiceCard _govfor;
    private readonly CmuChoiceCard _opfor;
    private readonly CmuChoiceCard _other;

    public JoinRoundWindow()
    {
        Title = Loc.GetString("cmu-lobby-join-round-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // The button alternates left and right down the list, and that is doing work rather than
        // decoration: four identical rows read as a table you scan past, whereas a zig-zag makes
        // each card its own object and forces the eye to stop at each one.
        _colonists = AddCard("lobby-state-ready-button-join-state", "cmu-lobby-join-colonists-desc", ColonistsPalette, buttonOnLeft: true);
        _govfor = AddCard("rmc-lobby-join-govfor", "cmu-lobby-join-govfor-desc", GovforPalette, buttonOnLeft: false);
        _opfor = AddCard("rmc-lobby-join-opfor", "cmu-lobby-join-opfor-desc", OpforPalette, buttonOnLeft: true);
        _other = AddCard("rmc-lobby-join-other", "cmu-lobby-join-other-desc", OtherPalette, buttonOnLeft: false);

        ApplyCrtPalette();

        _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    private CmuChoiceCard AddCard(string buttonKey, string descKey, CmuChoiceCard.Palette palette, bool buttonOnLeft)
    {
        var card = new CmuChoiceCard(
            Loc.GetString(buttonKey),
            Loc.GetString(descKey),
            palette,
            buttonOnLeft);

        Choices.AddChild(card);
        return card;
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    private void OnCrtUiEnabledChanged(bool _)
    {
        ApplyCrtPalette();
    }

    private void OnCrtUiColorChanged(string _)
    {
        ApplyCrtPalette();
    }

    private void ApplyCrtPalette()
    {
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);

        // After the theme walk, never before. ApplyWindow re-tags every control in the tree and hands
        // the buttons the shared CrtButton box; anything set earlier would simply be replaced.
        _colonists.ApplyPalette();
        _govfor.ApplyPalette();
        _opfor.ApplyPalette();
        _other.ApplyPalette();
    }
}
