using Content.Client._CMU14.Interface;
using Content.Client.Stylesheets;
using Content.Shared.CCVar;
using Content.Shared.Administration.Managers;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ObserveWarningWindow : DefaultWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private ISharedAdminManager _adminManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;
    [Dependency] private IStylesheetManager _stylesheetManager = default!;

    public ObserveWarningWindow()
    {
        Title = Loc.GetString("observe-warning-window-title");
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CrtOverlay.Source = CrtContent;

        ApplyCrtPalette();
        var player = _playerManager.LocalSession;

        if (player != null && _adminManager.IsAdmin(player))
        {
            ObserveButton.Text = Loc.GetString("observe-as-player");
            ObserveAsAdminButton.Visible = true;
            ObserveAsAdminButton.OnPressed += _ => { this.Close(); };
        }

        ObserveButton.OnPressed += _ => { this.Close(); };
        NevermindButton.OnPressed += _ => { this.Close(); };
        _cfg.OnValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.OnValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    [Obsolete("Controls should only be removed from UI tree instead of being disposed")]
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _cfg.UnsubValueChanged(CCVars.CrtUiEnabled, OnCrtUiEnabledChanged);
        _cfg.UnsubValueChanged(CCVars.CrtUiColor, OnCrtUiColorChanged);
    }

    private void OnCrtUiEnabledChanged(bool _)
    {
        ApplyCrtPalette();
    }

    private void OnCrtUiColorChanged(string _)
    {
        ApplyCrtPalette();
    }

    private void ApplyCrtPalette()
    {
        Stylesheet = _stylesheetManager.SheetNano;
        CrtLobbyTheme.ApplyWindow(this, useCrtTypography: true);
        ApplyButtonColors();
    }

    /// <summary>
    ///     Caution for the two ways this ends normally, Danger for the one that keeps admin powers on
    ///     a ghost - the same severity language StaffHelpWindow uses for its faction cards.
    /// </summary>
    /// <remarks>
    ///     This used to hand-roll its own StyleBoxes here. <see cref="CmuButtonStyles"/> now owns the
    ///     variant set, including the uniform content margins - the mismatch between
    ///     <c>CrtAttentionButton</c> and a plain <see cref="Button"/> is what made Nevermind's label
    ///     sit closer to its left edge than the other two.
    /// </remarks>
    private void ApplyButtonColors()
    {
        CmuButtonStyles.Apply(ObserveButton, CmuButtonStyles.Variant.Caution);
        CmuButtonStyles.Apply(NevermindButton, CmuButtonStyles.Variant.Caution);
        CmuButtonStyles.Apply(ObserveAsAdminButton, CmuButtonStyles.Variant.Danger);
    }
}
