using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ColorNaming;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._CMU14.UserInterface.ColorPicker;

/// <summary>
///     A colour control that reads as a sentence: a swatch, the colour described in words and shown
///     in that colour, and an editable hex field. The picking surface expands underneath it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CmuColorPicker : Control
{
    private const string ArrowCollapsed = "▼";
    private const string ArrowExpanded = "▲";

    [Dependency] private readonly ILocalizationManager _localization = default!;

    private Color _color = Color.White;
    private string? _paletteId;

    /// <summary>
    ///     Text placed before the colour's name, e.g. "Your highlight color is:".
    /// </summary>
    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    /// <summary>
    ///     Id of a <c>palette</c> prototype whose colours are offered as presets.
    /// </summary>
    public string? PaletteId
    {
        get => _paletteId;
        set
        {
            _paletteId = value;
            Panel.SetPalette(value);
        }
    }

    public Color Color
    {
        get => _color;
        set
        {
            _color = value;
            Panel.Color = value;
            UpdateDisplay();
        }
    }

    public event Action<Color>? OnColorChanged;

    public CmuColorPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Panel.OnColorPicked += color =>
        {
            _color = color;
            UpdateDisplay();
            OnColorChanged?.Invoke(color);
        };

        SwatchButton.OnPressed += _ =>
        {
            Panel.Visible = !Panel.Visible;
            UpdateDisplay();
        };

        UpdateDisplay();
    }

    private void UpdateDisplay()
    {
        SwatchButton.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = _color,
            // Deliberately not a palette colour: this border frames whatever the player picked, and
            // a CRT green baked in here would go stale when they change the theme colour.
            BorderColor = Color.White.WithAlpha(0.35f),
            BorderThickness = new Thickness(1),
        };

        // The arrow sits on the swatch, so it has to flip against whatever was picked or it
        // disappears at one end of the range.
        SwatchArrow.Text = Panel.Visible ? ArrowExpanded : ArrowCollapsed;
        SwatchArrow.FontColorOverride = IsLight(_color) ? Color.Black : Color.White;

        // Only the name takes the colour - the "Your highlight color is:" prefix stays readable.
        NameLabel.Text = ColorNaming.Describe(_color, _localization);
        NameLabel.FontColorOverride = _color;
    }

    private static bool IsLight(Color color)
    {
        return color.R * 0.299f + color.G * 0.587f + color.B * 0.114f > 0.55f;
    }
}
